name: .NET

on:
  push:
    branches:
    - master
    - release/*

  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest
    environment: Test

    # copy secrets to environment variables
    env:
      TEST_ENVIRONMENT_INITIALIZED: true
      OTPRAVKA_USER_PASSWORD: '${{secrets.OTPRAVKA_USER_PASSWORD}}'
      OTPRAVKA_USER_PHONE: '${{secrets.OTPRAVKA_USER_PHONE}}'
      OTPRAVKA_ACCESS_TOKEN: '${{secrets.OTPRAVKA_ACCESS_TOKEN}}'
      OTPRAVKA_USER_EMAIL: '${{secrets.OTPRAVKA_USER_EMAIL}}'

    steps:

    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
